### ISSUE TITLE
Fetch User Mentions and Organize Comments by Issue

### ISSUE THREAD

**Issue by rluijk** [Synestheticminds/UnderdogCowboy#122]
**Description:**

Create a Python script that fetches comments mentioning specific users (from a list provided as an array via arguments). The script should gather the issue details, all its comments, and specifically highlight the most recent comment mentioning each user. The output should be a Python object containing:
1. The issue details.
2. All its comments.
3. The specific comment that requires the user's attention (the last mentioned one).

The goal of the script is to prepare feature integration in the GitHub part of the interactive storage layer.
When this issue is done 
- [ ] decide and implement on class system around github API calls.
The current is perhaps a bit to small for all use cases

---

### Tasks:
- [ ] **Accept Usernames as Input**:
  Accept a list of usernames as a command-line argument or function input. Use the following snippet to handle command-line input:
  ```python
  import sys

  # Get list of usernames from command-line arguments
  usernames = sys.argv[1:]  # Example usage: python script.py user1 user2 user3
  if not usernames:
      print("Please provide a list of usernames.")
      sys.exit(1)
  print(f"Fetching mentions for: {usernames}")
  ```

- [ ] **Fetch Issues and Comments**:
  Use the GitHub GraphQL API to fetch all issues and their comments. Here's a starting query and function:
  ```python
  query = """
  query {
    repository(owner: "OWNER_NAME", name: "REPO_NAME") {
      issues(last: 50) {
        nodes {
          number
          title
          url
          comments(last: 50) {
            nodes {
              body
              createdAt
              author {
                login
              }
            }
          }
        }
      }
    }
  }
  """

  import requests

  def fetch_issues_and_comments(token):
      headers = {"Authorization": f"Bearer {token}"}
      response = requests.post(
          "https://api.github.com/graphql", json={"query": query}, headers=headers
      )
      if response.status_code == 200:
          return response.json()["data"]["repository"]["issues"]["nodes"]
      else:
          print(f"Error: {response.status_code} {response.text}")
          return []
  ```

- [ ] **Filter Mentions for Users**:
  Parse the comments to identify mentions for each user in the input list. Use the following logic:
  ```python
  def filter_mentions(issues, usernames):
      results = []
      for issue in issues:
          user_mentions = {}
          for comment in issue["comments"]["nodes"]:
              for username in usernames:
                  if f"@{username}" in comment["body"]:
                      user_mentions[username] = {
                          "body": comment["body"],
                          "author": comment["author"]["login"],
                          "created_at": comment["createdAt"],
                      }
          if user_mentions:
              results.append({
                  "issue": {
                      "number": issue["number"],
                      "title": issue["title"],
                      "url": issue["url"],
                  },
                  "comments": issue["comments"]["nodes"],
                  "mentions": user_mentions,
              })
      return results
  ```

- [ ] **Output Python Object**:
  Construct the final Python object for each issue, with all comments and the most recent mention per user:
  ```python
  def construct_output(filtered_mentions):
      for issue in filtered_mentions:
          print(f"Issue #{issue['issue']['number']} - {issue['issue']['title']}")
          print(f"URL: {issue['issue']['url']}")
          print("Last Mentions:")
          for username, mention in issue["mentions"].items():
              print(f"  @{username}: {mention['body']} (by {mention['author']} at {mention['created_at']})")
          print()
  ```

- [ ] **Error Handling and Testing**:
  - Handle API errors and rate limits.
  - Test with various scenarios, such as:
    - Issues with no mentions.
    - Multiple mentions of the same user in an issue.
    - Multiple users with mentions in the same issue.

---

### Example Usage:
Run the script from the command line:
```bash
python script.py user1 user2 user3
```

Example output for an issue:
```plaintext
Issue #42 - Fix authentication bug
URL: https://github.com/OWNER_NAME/REPO_NAME/issues/42
Last Mentions:
  @user1: Can you check this? (by user123 at 2024-12-27T10:15:00)
  @user2: Please review this section. (by user456 at 2024-12-27T12:30:00)
```
